### ISSUE TITLE
[Feature] Prettify your code every commit

### ISSUE THREAD

**Issue by jkopyto** [mateuszCabala95/CodersCamp2020.Bomberman#15]
Let's prettify our code implicitly running prettier every time we are committing changes:

- [x] `npm i -D husky lint-staged`
- [x] Add these to package.json:
```
"husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "*.{js,json,css,jsx,ts,tsx,html}": [
      "prettier --write",
      "git add"
    ]
  }
  ```
  
  As you can see husky will catch `git commit` command and will run `lint-staged`. Lint-staged will trigger `prettier --write` command and will prettify files that you are going to commit

**Comment by kgutka** [comment]
According to lint-staged documentation:

`
Prior to version 10, tasks had to manually include git add as the final step. This behavior has been integrated into lint-staged itself in order to prevent race conditions with multiple tasks editing the same files. If lint-staged detects git add in task configurations, it will show a warning in the console. Please remove git add from your configuration after upgrading.
`

we should remove `git add` from `lint-staged` configuration.

**Comment by mateuszCabala95** [comment]
zrobione
